spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: codecollab-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRY_MS}

judge0:
  api-url: ${JUDGE0_API_URL:https://judge0-ce.p.rapidapi.com}
  api-key: ${JUDGE0_API_KEY:}
